### ISSUE TITLE
The command /pinteract does not exist.

### ISSUE THREAD

**Issue by StarkITA** [plottingCreeper/FFXIV-scripts-and-macros#1]
After latest updates, the script Marketbotty gives this error:

> The command /pinteract does not exist.

Truth to be told, I have no idea which plogon gives access to this command, or if it is updated or not, but I figured I'd report it!

**Comment by gitBurmecia** [comment]
Pandora isn't updated yet

**Comment by StarkITA** [comment]
SND dev replied here (https://github.com/Jaksuhn/SomethingNeedDoing/issues/154#issuecomment-2206729360) and said that there is /interact in SND, in case
