### ISSUE TITLE
Error /click

### ISSUE THREAD

**Issue by midoom** [plottingCreeper/FFXIV-scripts-and-macros#2]
hello I have this error

> [SND] Failure while running /click select_retainer1 (step 32): Unexpected click error

**Comment by gitBurmecia** [comment]
The elements were renamed, there is a list in the help menu,  can simply replace them in your personal copy until a new script update.

**Comment by plottingCreeper** [comment]
Clicks have been updated on MarketBotty and FishingRaid.
